### ISSUE TITLE
Transport: Call to undefined method TSF_Extension_Manager\Extension\Transport\Logger\Server::get_flush_store()

### ISSUE THREAD

**Issue by JorindeUsMedia** [sybrew/The-SEO-Framework-Extension-Manager#71]
**Describe the bug**
When I'm running the Importer of the Transport extension I'm getting the following error:

```
PHP Fatal error:  Uncaught Error: Call to undefined method TSF_Extension_Manager\Extension\Transport\Logger\Server::get_flush_store() in /var/app/current/webapp/content/plugins/the-seo-framework-extension-manager/extensions/free/transport/trunk/inc/classes/handler.class.php:450
Stack trace:
#0 /var/app/current/webapp/content/plugins/the-seo-framework-extension-manager/extensions/free/transport/trunk/inc/classes/admin.class.php(366): TSF_Extension_Manager\Extension\Transport\Handler->_import(Array)
#1 /var/app/current/webapp/wp/wp-includes/class-wp-hook.php(308): TSF_Extension_Manager\Extension\Transport\Admin->_wp_ajax_transport('')
#2 /var/app/current/webapp/wp/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#3 /var/app/current/webapp/wp/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /var/app/current/webapp/wp/wp-admin/admin-ajax.php(188): do_action('wp_ajax_tsfem_e...')
#5 {main}
  thrown in /var/app/current/webapp/content/plugins/the-seo-framework-extension-manager/extensions/free/transport/trunk/inc/classes/handler.class.php on line 450
```

**To Reproduce**
1. Go to the Transport Extension
2. Choose Yoast SEO (I have only tested it with Yoast SEO)
3. Click on Import
4. On the right you see the error "∶ An unknown error occured. Please refresh this page and try again." The full error I got from our AWS logs. See above.

When I check the plugin code it seems `get_flush_store()` is indeed not a function on the Server Class.

**Comment by sybrew** [comment]
Thank you for the detailed report. I see I called the wrong class incorrectly: it should've been the Store, not Server.

This should only invoke when the service connection is interrupted or when an ancient browser is used. So it eluded my testing.

I shall have it fixed in the next update. Cheers!
